{1}{}{PID_TRASH@Все, что от вас требуется - это найти в хламе что-то, похожее на гильзу, что-то, похожее на пулю, сложить все это вокруг заряда сушеных грибов и собственным суровым видом придать этой поделке форму готового патрона. Повторять, пока не надоест.@SK_REPAIR 75@SK_REPAIR 75@PID_PUMP_PARTS 2&PID_MOUSE_SKIN 1@@PID_TRASH 5@exp 25 }
{2}{}{PID_10MM_JHP@Вы имеете дело с обыкновенными полуоболочечными пистолетными патронами. Примитивная свинцовая рубашка пули в металлической оболочке, гильза с зарядом бездымного пороха - все нарезается под копирку из металлических заготовок.@SK_REPAIR 100@SK_REPAIR 100@PID_CRAFT_IRON_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_10MM_JHP 20@exp 50 }
{3}{}{PID_10MM_AP@Слегка заостренные пули в крепкой стальной оболочке. Тогда как для гильзы можно использовать тонкий лист металла практически любого качества, оболочка пули использует самые твердые и прочные сплавы из доступных.@SK_REPAIR 125@SK_REPAIR 125@PID_CRAFT_IRON_PART 1&PID_CRAFT_STEEL_PART 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_10MM_AP 15@exp 50 }
{4}{}{PID_10MM_SPECIAL@С помощью фабрикатора будет не слишком трудно добиться идеальной балансировки пули и повышенния качества используемых материалов, так как фактически задача - уместить больше металла и больше пороха в тот же объем десятимиллиметровой пули.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_CRAFT_AUTOFIX 1@PID_10MM_SPECIAL 10@exp 75 }
{5}{}{PID_10MM_EX@При проектировании необходимо учесть, что заряд должен сохранять и без того невысокую силу взрыва при разрушении оболочки. В целом это все те же десятимиллиметровые патроны с небольшим зарядом гексогена вместо рубашки.@SK_REPAIR 125|SK_SCIENCE 125@SK_REPAIR 125&SK_SCIENCE 125@PID_CRAFT_STEEL_PART 2&PID_HEXOGEN 1&PID_GUNPOWDER 1@PID_CRAFT_AUTOFIX 1@PID_10MM_EX 12@exp 75 }
{6}{}{PID_45_CALIBER_AMMO@Массовый, легко воспроизводимый патрон. Свинцовая пуля в металлической оболочке, металлическая гильза с зарядом пороха. Ничего такого, что не мог бы выполнить начинающий кулибин, имея инструменты под рукой.@SK_REPAIR 100@SK_REPAIR 100@PID_CRAFT_IRON_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 11@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_45_CALIBER_AMMO 20@exp 50 }
{7}{}{PID_45_CALIBER_SPECIAL@Подбор высококачественных материалов, заводская балансировка, немного любви в процессе производства - при правильном изготовлении этот патрон, выполненный по довоенной технологии, сделает настоящее оружие даже из дамского пистолетика.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_CRAFT_AUTOFIX 1@PID_45_CALIBER_SPECIAL 10@exp 75 }
{8}{}{PID_5MM_JHP@Длинная винтовочная полуоболочечная пуля на длинной же гильзе. Работа без специализированного оборудования может занять продолжительное время из-за повышенного объема работ с гильзой и пороховым зарядом.@SK_REPAIR 125@SK_REPAIR 125@PID_CRAFT_STEEL_PART 1&PID_CRAFT_IRON_PART 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_5MM_JHP 10@exp 75 }
{9}{}{PID_5MM_AP@Утяжеленная пуля, требующая при изготовлении повышенного внимания к своей форме и качеству материала. Бронебойный сердечник, также позволяющий пуле сохранять единство структуры при прохождении препятствий, без заводского оборудования изготовить сложно, но возможно.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_5MM_AP 8@exp 100 }
{10}{}{PID_5MM_FRAG@Спроектировать утяжеленную, легко распадающуюся на фрагменты рубашку патрону такого мелкого калибра - задача не из легких. Фрагменты должны не слишком быстро деформироваться при прохождении через препятствие; при этом пуля должна обладать динамикой оригинала.@SK_REPAIR 150|SK_SCIENCE 125@SK_REPAIR 150&SK_SCIENCE 125@PID_CRAFT_STEEL_PART 1&PID_CRAFT_IRON_PART 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_CRAFT_AUTOFIX 1@PID_5MM_FRAG 8@exp 100 }
{11}{}{PID_7_62MM_AMMO@Так как речь идет о сравнительно крупнокалиберном патроне, об использовании низкокачественных материалов можно забыть. И пусть патроны НАТО все еще можно изготовить при помощи инструментов, не стоит ждать от них чудес, если тому, кто их использует, придется иметь дело с композитной броней.@SK_REPAIR 140|SK_SCIENCE 100@SK_REPAIR 140&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_7_62MM_AMMO 8@exp 125 }
{12}{}{PID_7_62MM_AP@Утяжеление боеприпаса сердечником и твердой оболочкой влечет за собой увеличение порохового заряда. И все это вместе ведет к снижению количества боеприпасов из того же сырья и заметному усложнению производства. К тому же калибр слишком велик, чтобы несколько часов кряду кропеть над структурой каждой пули, так что без фабрикатора здесь явно не обойтись.@SK_REPAIR 140|SK_SCIENCE 100@SK_REPAIR 140&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_CRAFT_AUTOFIX 1@PID_7_62MM_AP 5@exp 150 }
{13}{}{PID_14MM_AP@Боеприпас обладает не идеальной аэродинамикой, что вкупе с укладкой всего порохового заряда строго за пулей образует интересную конструкцию бронебойного снаряда для короткой дистанции, чего-то среднего между пулей 12 калибра и экспансивным крупнокалиберным пистолетным патроном. К форме и качеству изготовления рубашки и сердечника снаряда стоит уделять повышенное внимание - они не должны деформироваться и терять много энергии при соприкосновении с твердой поверхностью.@SK_REPAIR 140|SK_SCIENCE 100@SK_REPAIR 140&SK_SCIENCE 120@PID_CRAFT_STEEL_PART 4&PID_CRAFT_LEAD 1&PID_GUNPOWDER 2@PID_CRAFT_AUTOFIX 1@PID_14MM_AP 9@exp 200 }
{14}{}{PID_HUNTING_SHELLS@Этот вид патронов при желании можно изготовить просто при помощи подручных средств. Гильза из прочной ткани или целлюлозы, капсюль и прочие мелкие детали изготавливаются из металла любого качества. Начинка в виде мелкой свинцовой картечи в тонкой железной рубашке. Дешево и сердито.@SK_REPAIR 100@SK_REPAIR 100@PID_CRAFT_IRON_PART 1&PID_RAGS 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@@PID_HUNTING_SHELLS 11@exp 50 }
{15}{}{PID_SHOTGUN_SHELLS@Боевому дробовику - боевая картечь. Крупные, по сравнению с охотничьими, дробины в стальной рубашке хищно глядят на вас из полной баллистита целлюлозной гильзы. Мурашки по коже!@SK_REPAIR 125@SK_REPAIR 100@PID_CRAFT_STEEL_PART 1&PID_RAGS 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SHOTGUN_SHELLS 7@exp 75 }
{16}{}{PID_ASSAULT_SHELLS@Сделать стальную гильзу заводского качества и спрессовать в ней мощный пороховой заряд вряд ли возможно без станка. А создать тяжелую твердосплавную пулю, к тому же аэродинамичную - и подавно. Заводи свой агрегат и переубеди мир в том, что тяжелая броня хорошо защитит от любого дробовика.@SK_REPAIR 160|SK_SCIENCE 130@SK_REPAIR 160&SK_SCIENCE 130@PID_CRAFT_STEEL_PART 3&PID_CRAFT_LEAD 1&PID_GUNPOWDER 2@PID_CRAFT_AUTOFIX 1@PID_ASSAULT_SHELLS 5@exp 150 }
{17}{}{PID_DB_SHELLS@Капсула с липким топливом и игольчатыми патронами из магния не должна повреждаться до самого выстрела, а гильза - сгореть в затворе. Нерасходуемые части боеприпаса выполняются из высокопрочного полимера, во избежание.@SK_REPAIR 150|SK_SCIENCE 150@SK_REPAIR 150&SK_SCIENCE 150@PID_CRAFT_IRON_PART 1&PID_MINERAL 1&PID_CRAFT_POLYMER 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_CRAFT_AUTOFIX 1@PID_DB_SHELLS 6@exp 150 }
{18}{}{PID_44_MAGNUM_JHP@Займемся патронами .44 магнум, классикой S&W. Боеприпас стандартной револьверной формы, обе стороны гильзы идеально перепендикулярны друг другу от фланца и до самого края. Надеюсь, вы прихватили все необходимые измерительные приборы.@SK_REPAIR 110@SK_REPAIR 110@PID_CRAFT_IRON_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_44_MAGNUM_JHP 14@exp 50 }
{19}{}{PID_44_FMJ_MAGNUM@Классический для гражданских револьверов патрон в амплуа утяжеленного цельнометаллического поедателя легкой брони. Шляпка при изготовлении слегка заостряется и центр тяжести незначительно смещается в ее сторону.@SK_REPAIR 140|SK_SCIENCE 75@SK_REPAIR 140&SK_SCIENCE 75@PID_CRAFT_IRON_PART 1&PID_CRAFT_STEEL_PART 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_44_FMJ_MAGNUM 9@exp 75 }
{20}{}{PID_SMALL_ENERGY_CELL@При помощи комбинатора нужно получить минеральный ионный электролит, который затем устанавливается в корпус из металла и пластмассового изолятора с контактом и соединенным с "начинкой" катодом. Питания одной батареи должно хватить даже на выстрел из низковольтного энергооружия.@SK_REPAIR 100|SK_SCIENCE 150@SK_REPAIR 100&SK_SCIENCE 150@PID_CRAFT_IRON_PART 1&PID_CRAFT_POLYMER 1&PID_V15_COMPUTER_PART 1&PID_MINERAL 1@PID_CRAFT_AUTOFIX 1@PID_SMALL_ENERGY_CELL 25@exp 100 }
{21}{}{PID_SMALL_ENERGY_CELL_IO@При помощи комбинатора нужно получить минеральный ионный электролит, который затем устанавливается в корпус из металла и пластмассового изолятора с контактом и соединенным с "начинкой" катодом. Ко всему этому добавляется ионизатор с собственным источником питания и триггером, направляющим его заряд на сами системы оружия.@SK_REPAIR 130|SK_SCIENCE 175@SK_REPAIR 130&SK_SCIENCE 175@PID_CRAFT_IRON_PART 1&PID_CRAFT_POLYMER 1&PID_V15_COMPUTER_PART 2&PID_MINERAL 2@PID_CRAFT_AUTOFIX 1@PID_SMALL_ENERGY_CELL_IO 25@exp 150 }
{22}{}{PID_MICRO_FUSION_CELL@По сути целевой продукт оправдывает свое название - это микроскопический реактор, который генерирует энергию для сети, с которой соединен. Собирается в корпусе большой батареи с зарядом дейтерия.@SK_REPAIR 150|SK_SCIENCE 175@SK_REPAIR 150&SK_SCIENCE 175@PID_CRAFT_STEEL_PART 1&PID_V15_COMPUTER_PART 1&PID_CRAFT_LEAD 1&PID_CRAFT_URANIUM 1@PID_CRAFT_AUTOFIX 1@PID_MICRO_FUSION_CELL 10@exp 175 }
{23}{}{PID_223_FMJ@В общих чертах, мы имеем дело с обыкновенной пулей диаметром 5,56 миллиметров образца НАТО с утонченной рубашкой из твердой стали. Цельнометаллическая пуля при изготовлении не должна получиться слишком тяжелой; гильзу нельзя делать тонкой во избежание смятия при хранении.@SK_REPAIR 140|SK_SCIENCE 100@SK_REPAIR 140&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_223_FMJ 10@exp 100 }
{24}{}{PID_223_AP@Пуля диаметром 5,56 миллиметров образца НАТО с бронебойным сердечником, плавно переходящим в крепкую заостренную стальную рубашку. С таким заострением следует уделять внимание тому, чтобы пуля на выходе не потеряла свою аэродинамичность.@SK_REPAIR 150|SK_SCIENCE 110@SK_REPAIR 150&SK_SCIENCE 110@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_223_AP 7@exp 125 }
{25}{}{PID_9MM_AMMO@Весьма требовательный к качеству калибр. Для выполнения сравнительно короткой гильзы с изогнутым фланцем потребуется либо большая усидчивость, либо оборудование, которое сделает пыльную работу за вас.@SK_REPAIR 115@SK_REPAIR 115@PID_CRAFT_IRON_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_9MM_AMMO 14@exp 75 }
{26}{}{PID_9MM_BALL@То, что патрон удобен в хранении и использовании, еще не значит, что он удобен в изготовлении. Работу с короткой гильзой, заострением и аэродинамикой пули с ее ровной укладкой над пороховым зарядом осилят только самые усидчивые мастера.@SK_REPAIR 145|SK_SCIENCE 110@SK_REPAIR 145&SK_SCIENCE 110@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_9MM_BALL 12@exp 100 }
{27}{}{PID_4_7MM_CASELESS@Мелкокалиберные пули делаются слегка заостренными и оснащаются короткими сверхлегкими полимерными картриджами, которые полностью сгорают в затворе вместе с порохом при выстреле. Ни в коем случае нельзя допускать осечки при выстреле - затворы безгильзовых оружий не оснащены гильзоотводами, поэтому извлечь давший осечку патрон в полевых условиях будет непросто.@SK_REPAIR 160|SK_SCIENCE 130@SK_REPAIR 160&SK_SCIENCE 130@PID_CRAFT_STEEL_PART 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1&PID_CRAFT_POLYMER 1@PID_CRAFT_AUTOFIX 1@PID_4_7MM_CASELESS 12@exp 125 }
{28}{}{PID_4_7MM_AP@Мелкокалиберные пули утяжеляются бронебойным сердечником и сверхпрочной рубашкой. Сгорающие при выстреле картриджи заполняются усиленным зарядом пороха; подобные боеприпасы делаются с расчетом на повышенную прочность, чтобы не допустить их поломки в затворе оружия.@SK_REPAIR 175&PE_SWIFT_LEARNER 1|SK_SCIENCE 140&PE_SWIFT_LEARNER 1@SK_REPAIR 175&SK_SCIENCE 140@PID_CRAFT_STEEL_PART 1&PID_CRAFT_LEAD 1&PID_GUNPOWDER 1&PID_CRAFT_POLYMER 1@PID_CRAFT_AUTOFIX 1@PID_4_7MM_AP 8@exp 175 }
{29}{}{PID_2MM_EC_AMMO@Сама пуля представляет собой ювелирно изготовленную иглу диаметром в два миллиметра с ферромагнетиком для ускорения магнитным полем, и боевой структурой из сердечника и пробивающего острия, выполненных из прочнейшей стали. Пластиковый картридж оснащается ионной батареей для зарядки оружия.@SK_REPAIR 180&PE_SWIFT_LEARNER 1|SK_SCIENCE 180&PE_SWIFT_LEARNER 1@SK_REPAIR 180&SK_SCIENCE 180@PID_CRAFT_STEEL_PART 1&PID_V15_COMPUTER_PART 1&PID_CRAFT_POLYMER 1&PID_SMALL_ENERGY_CELL 5@PID_CRAFT_AUTOFIX 1@PID_2MM_EC_AMMO 5@exp 200 }
{30}{}{PID_700_NITRO_EXPRESS@Крупного размера боеприпас для однозарядных штуцеров. В длинную ровную гильзу, доверху заправленную порохом, сверху вставляется обтекаемая широкая пуля в тонкой полимерной прокладке. Выполнить снаряд такого размера из металла труднее, чем кажется на первый взгляд.@SK_REPAIR 175&PE_SWIFT_LEARNER 1|SK_SCIENCE 125&PE_SWIFT_LEARNER 1@SK_REPAIR 175&SK_SCIENCE 125@PID_CRAFT_STEEL_PART 4&PID_CRAFT_LEAD 1&PID_GUNPOWDER 4&PID_CRAFT_POLYMER 1@PID_CRAFT_AUTOFIX 1@PID_700_NITRO_EXPRESS 3@exp 175 }
{31}{}{PID_40MM@Гранатометный боеприпас общего назначения включает в себя снаряд с повышенным зарядом взрывчатки и механическим триггером-детонатором, и гильзы с пороховым зарядом для произведения выстрела. Стальная рубашка должна не только формировать осколки, но и уберегать снаряд от вероятной детонации без срабатывания триггера.@SK_REPAIR 175|SK_SCIENCE 150@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_STEEL_PART 3&PID_CRAFT_POLYMER 1&PID_GUNPOWDER 1&PID_HEXOGEN 3@PID_CRAFT_AUTOFIX 1@PID_40MM 1@exp 175 }
{32}{}{PID_40MM_HEAT@Этот боеприпас для гарантометов оснащается усиленным пороховым зарядом для повышенной скорости при спуске. Снаряд имеет заостренную форму за счет бронебойной рубашки, в которой также располагается кумулятивная выемка. В случае отсутствия прямого попадания триггер должен моментально детонировать заряд.@SK_REPAIR 180&PE_SWIFT_LEARNER 1|SK_SCIENCE 160&PE_SWIFT_LEARNER 1@SK_REPAIR 180&SK_SCIENCE 160@PID_CRAFT_STEEL_PART 4&PID_CRAFT_POLYMER 1&PID_GUNPOWDER 2&PID_HEXOGEN 3@PID_CRAFT_AUTOFIX 1@PID_40MM_HEAT 1@exp 200 }
{33}{}{PID_EXPLOSIVE_ROCKET@Разрывная боеголовка с детонатором устанавливается на ускоритель с зарядом нитроглицеринового пороха и пирозамедлителя. Снаряду придается обтекаемая аэродинамичная форма, чтобы он не сбивался с траектории полета и не терял высоту слишком быстро.@SK_REPAIR 180|SK_SCIENCE 160@SK_REPAIR 180&PE_SWIFT_LEARNER 1&SK_SCIENCE 160&PE_SWIFT_LEARNER 1@PID_CRAFT_STEEL_PART 4&PID_STEEL 1&PID_CRAFT_POLYMER 2&PID_GUNPOWDER 2&PID_HEXOGEN 7&PID_MINERAL 1@PID_CRAFT_AUTOFIX 1@PID_EXPLOSIVE_ROCKET 1@exp 200 }
{34}{}{PID_ROCKET_AP@Боеголовка оснащается заостренным бронебойным урановым наконечником, который в случае разрыва вне плотной преграды формирует крупные осколки, получающие ускорение от основной энергии взрыва. Двигатель все еще представлен шашкой с нитроглицериновым порохом и пирозамедлителем.@SK_REPAIR 180&PE_SWIFT_LEARNER 1|SK_SCIENCE 180&PE_SWIFT_LEARNER 1@SK_REPAIR 180&SK_SCIENCE 180@PID_CRAFT_URANIUM_PLATE 1&PID_CRAFT_STEEL_PART 1&PID_STEEL 1&PID_CRAFT_POLYMER 2&PID_GUNPOWDER 3&PID_HEXOGEN 6&PID_MINERAL 1@PID_CRAFT_AUTOFIX 1@PID_ROCKET_AP 1@exp 225 }
{94}{}{PID_ZIP_GUN@Задача довольно проста - придать металлическим трубам форму деталей рамы, рукояти и ствола, сделать барабан из цельного куска металла и соединить курок со спусковым крючком взводной пружиной.@SK_REPAIR 100@SK_REPAIR 100@PID_PUMP_PARTS 25@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_ZIP_GUN 1@exp 100 }
{95}{}{PID_SPRINGER_RIFLE@В куске трубы делается отверстие для скользяще-поворотного затвора, взводящего спусковой механизм. "Магазин" преставлен выемкой под патроны, где основной механизм заряжания - элементарная сила тяготения.@SK_REPAIR 100@SK_REPAIR 100@PID_PUMP_PARTS 35@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SPRINGER_RIFLE 1@exp 100 }
{96}{}{PID_SHITCANNON@Кассета под патроны из цилиндра и старой пружины подает патроны по одному в рычажной затвор. Все это обшивается громоздким металлическим корпусом для пафоса.@SK_REPAIR 100@SK_REPAIR 100@PID_PUMP_PARTS 60@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SHITCANNON 1@exp 100 }
{97}{}{PID_CRAPSHOTGUN@Из двух труб выполняются гладкие стволы, из пружины с рычагом - подобие переломного затвора, взводящего бойки. В стволах делаются небольшие неровности по размеру патрона, которые деформируют пулю на спуске за счет медленного сгорания пороха.@SK_REPAIR 100@SK_REPAIR 100@PID_PUMP_PARTS 55@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SHITCANNON 1@exp 100 }
{98}{}{PID_MULTI_BARREL_GUN@Оружие оснащается упрощенным механизмом отвода пороховых газов для автоматической стрельбы и длинным магазионм с пружиной. Для оружия выполняется простенький корпус из относительно ровных металлических листов.@SK_REPAIR 100@SK_REPAIR 100@PID_PUMP_PARTS 55@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_MULTI_BARREL_GUN 1@exp 100 }
{99}{}{PID_SHIT_AUTORIFLE@Классический спусковой механизм Томпсона в трубе с присобаченным снизу магазином. Вот и вся нехитрая конструкция, за исключением выполненных из найденной на помойке пробки приклада и цевья.@SK_REPAIR 100@SK_REPAIR 100@PID_PUMP_PARTS 65@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SHIT_AUTORIFLE 1@exp 100 }
{100}{}{PID_KNIFE@Длинная металлическая заготовка выпрямляется, выравнивается. Одному концу придается форма лезвия, которое впоследствие затачивается: второму просто достаточно придать форму рукояти - все равно сломается такое орудие сравнительно быстро.@SK_REPAIR 50@SK_REPAIR 50@PID_CRAFT_IRON_PART 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_KNIFE 1@exp 100 }
{101}{}{PID_COMBAT_KNIFE@Лезвие изгибается, балансируется и затачивается до бритвенной остроны с рассчетом на то, что нож делается для боя или охоты и никогда не будет лежать без дела. К нему добавляется удобная рукоять из дерева, обитая кожей.@SK_REPAIR 100@SK_REPAIR 100@PID_CRAFT_STEEL_PART 1&PID_STEEL 1&PID_CRAFT_WOOD 1&PID_CRAFT_LEATHER 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_COMBAT_KNIFE 1@exp 250 }
{102}{}{PID_LIL_JESUS_WEAPON@С тыльной стороны прочного хромированного лезвия наносятся мелкие зазубрины, конец слегка изгибается назад. Все это насаживается на удобную резиновую рукоять с металлическим узором. Помните, что дичь, на которую будут охотиться с этим ножом, скорее всего окажется двуногой.@SK_REPAIR 125|SK_OUTDOORSMAN 75@SK_REPAIR 125&SK_OUTDOORSMAN 75@PID_CRAFT_STEEL_PART 2&PID_STEEL 1&PID_CRAFT_POLYMER 1&PID_MINERAL 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_LIL_JESUS_WEAPON 1@exp 500 }
{103}{}{PID_RIPPER@Нож "Потрошитель" представляет из себя небольшую электропилу. Механизм вращает натянутую подвижную часть между шестернями-звеньями, а встроенный в рукоять микрореактор обеспечивает ему питание на очень продолжительный срок.@SK_REPAIR 175|SK_OUTDOORSMAN 150|SK_SCIENCE 125@SK_REPAIR 175&SK_OUTDOORSMAN 150&SK_SCIENCE 125@PID_CRAFT_CARBON 1&PID_CRAFT_URANIUM_PLATE 1&PID_CRAFT_STEEL_PART 10&PID_STEEL 15&PID_CRAFT_POLYMER 5&PID_MICRO_FUSION_CELL 1&PID_V15_COMPUTER_PART 3@PID_CRAFT_AUTOFIX 1@PID_RIPPER 1@exp 1750 }
{104}{}{PID_SLEDGEHAMMER@Тяжелый свинцовый молот насаживается на крепкую деревянную рукоять. И всё.@SK_REPAIR 60|SK_OUTDOORSMAN 60@SK_REPAIR 60&SK_OUTDOORSMAN 60@PID_CRAFT_LEAD 4&PID_CRAFT_WOOD 1@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SLEDGEHAMMER 1@exp 150 }
{105}{}{PID_SUPER_SLEDGE@Кинетический накопитель и мощный пневматический привод приводятся в действие срабатывающими в момент удара триггерами. Питание осуществляется при помощи двух микрореакторов, обеспечивающих оружию емкий энергоресурс. Ударная поверхность изготавливается из сверхпрочной урановой пластины.@SK_REPAIR 200|SK_OUTDOORSMAN 175|SK_SCIENCE 150@SK_REPAIR 200&SK_OUTDOORSMAN 175&SK_SCIENCE 150@PID_CRAFT_URANIUM_PLATE 2&PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 40&PID_STEEL 10&PID_CRAFT_POLYMER 5&PID_V15_COMPUTER_PART 4&PID_MICRO_FUSION_CELL 2@PID_CRAFT_AUTOFIX 1@PID_SUPER_SLEDGE 1@exp 2000 }
{106}{}{PID_BRASS_KNUCKLES@На свинчатку, служащую рукоятью, насаживается классический кастет из четырех влитых друг в друга колец.@SK_REPAIR 50@SK_REPAIR 50@PID_CRAFT_IRON_PART 1&PID_CRAFT_LEAD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_BRASS_KNUCKLES 1@exp 100 }
{107}{}{PID_SPIKED_KNUCKLES@Кастет классической формы влитых друг в друга колец изготавливается из высокопрочной стали со свинцовыми вкладками, балансирующими его вес. Область удара беспощадно усиливается острыми шипами.@SK_REPAIR 100@SK_REPAIR 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SPIKED_KNUCKLES 1@exp 250 }
{108}{}{PID_POWER_FIST@Пневмокастет представляет из себя перчатку с механизированной ударной областью на подвижных пневматических приводах. Внутри она обивается пористой резиной и оснащается надежными креплениями, не позволяющими кастету слететь. Чтобы постоянно не менять батареи, в качестве источника питания можно использовать микрореактор.@SK_REPAIR 160|SK_OUTDOORSMAN 140|SK_SCIENCE 120@SK_REPAIR 160&SK_OUTDOORSMAN 140&SK_SCIENCE 120@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 15&PID_STEEL 5&PID_CRAFT_POLYMER 5&PID_V15_COMPUTER_PART 2&PID_MICRO_FUSION_CELL 1@PID_CRAFT_AUTOFIX 1@PID_POWER_FIST 1@exp 1500 }
{109}{}{PID_MEGA_POWER_FIST@Силовые сервоприводы, питаемые атомными миниреакторами, оснащаются встроенными компенсаторами отдачи. Ударная поверхность и стояки приводов выполняются из обедненного урана для повышения прочности. Готовый силовой кастет рекомендуется оснастить дополнительными креплениями, прочно фиксирующими его на руке.@SK_REPAIR 200|SK_OUTDOORSMAN 180|SK_SCIENCE 150@SK_REPAIR 200&SK_OUTDOORSMAN 180&SK_SCIENCE 150@PID_CRAFT_URANIUM_PLATE 2&PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 20&PID_STEEL 8&PID_CRAFT_POLYMER 8&PID_V15_COMPUTER_PART 4&PID_MICRO_FUSION_CELL 2@PID_CRAFT_AUTOFIX 1@PID_MEGA_POWER_FIST 1@exp 2000 }
{110}{}{PID_SPEAR@Металлическое лезвие, как следует примотанное к деревянному древку веревкой.@SK_REPAIR 50@SK_REPAIR 50@PID_CRAFT_IRON_PART 2&PID_CRAFT_WOOD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SPEAR 1@exp 100 }
{111}{}{PID_SHARP_SPEAR@Древко тщательно полируется. Хитроумными креплениями к нему присоединяется острый длинный стальной наконечник с одного конца и твердое навершие - с другого.@SK_REPAIR 100@SK_REPAIR 100@PID_CRAFT_STEEL_PART 2&PID_CRAFT_LEAD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SHARP_SPEAR 1@exp 250 }
{112}{}{PID_TURBOTHRUST@Урановое лезвие оснащается кинетическим накопителем с мощным приводом, моментально высвобождающим всю свою силу в один мощный толчок в момент удара. Древко копья для ударо- и износостойкости выполняется из облегченного металла.@SK_REPAIR 200|SK_OUTDOORSMAN 175|SK_SCIENCE 150@SK_REPAIR 200&SK_OUTDOORSMAN 175&SK_SCIENCE 150@PID_CRAFT_URANIUM_PLATE 2&PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 40&PID_STEEL 10&PID_V15_COMPUTER_PART 2&PID_MICRO_FUSION_CELL 2@PID_CRAFT_AUTOFIX 1@PID_TURBOTHRUST 1@exp 2000 }
{200}{}{PID_10MM_PISTOL@Полуавтоматический десятимиллиметровый пистолет системы "Кольт". Оснащается стандартным самозарядным механизмом: остаточная энергия выстрела для выброса гильзы отводит затвор, который взводит курок и затем защелкивается обратно под давлением возвратной пружины.@SK_REPAIR 125|SK_SCIENCE 75@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 8&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 2&PID_STEEL 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_10MM_PISTOL 1@exp 250 }
{201}{}{PID_M1911@Полуавтоматический пистолет системы "Кольт" сорок пятого калибра. Оснащается стандартным самозарядным механизмом: остаточная энергия выстрела для выброса гильзы отводит затвор, который взводит курок и затем защелкивается обратно под давлением возвратной пружины.@SK_REPAIR 125|SK_SCIENCE 75@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 8&PID_METAL_TRASH 2&PID_CRAFT_STEEL_PART 2&PID_STEEL 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_M1911 1@exp 250 }
{202}{}{PID_DESERT_EAGLE@Полуавтоматический "Пустынный Орел", который до войны так воспевал кинематограф, под пафосным корпусом имеет обычный самозарядный пистолетный механизм. Реплецируется конструкция под популярный револьверный сорок четвертый калибр.@SK_REPAIR 140|SK_SCIENCE 90@SK_REPAIR 140&SK_SCIENCE 90@PID_CRAFT_IRON_PART 9&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 5&PID_STEEL 3@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_DESERT_EAGLE 1@exp 275 }
{203}{}{PID_DESERT_EAGLE_EXT_MAG@Полуавтоматический "Пустынный Орел", который до войны так воспевал кинематограф, под пафосным корпусом имеет обычный самозарядный пистолетный механизм. Реплецируется конструкция под популярный револьверный сорок четвертый калибр, дополнительно оснащаясь увеличенным магазином.@SK_REPAIR 140&PE_PACK_RAT 1|SK_SCIENCE 90&PE_PACK_RAT 1@SK_REPAIR 140&SK_SCIENCE 90@PID_CRAFT_IRON_PART 9&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 5&PID_STEEL 3@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 275 }
{204}{}{PID_44_MAGNUM_REVOLVER@Говоря "Револьвер Магнум", люди в 95% случаев подразумевают это творение дядюшек Смитта и Вессона, револьвер двойного действия двадцать девятой модели. Мощный револьверный калибр требует создания крепкой стальной рамы для избежания поломок при стрельбе.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_IRON_PART 3&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 10&PID_STEEL 2&PID_CRAFT_WOOD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_44_MAGNUM_REVOLVER 1@exp 275 }
{205}{}{PID_44_MAGNUM_SPEEDLOADER@Говоря "Револьвер Магнум", люди в 95% случаев подразумевают это творение дядюшек Смитта и Вессона, револьвер двойного действия двадцать девятой модели. Мощный револьверный калибр требует создания крепкой стальной рамы для избежания поломок при стрельбе. Оснащается экстрактором для гильз и заряжателем.@SK_REPAIR 150&PE_PACK_RAT 1|SK_SCIENCE 100&PE_PACK_RAT 1@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_IRON_PART 3&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 10&PID_STEEL 3&PID_CRAFT_WOOD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 275 }
{206}{}{PID_LASER_PISTOL@Маломощный лазерный пистолет в корпусе из прочной пластмассы начиняется тысячевольтной сетью с лазерным проектором. Батареи заряжаются в магазин комплектом и расходуют заряд по очереди.@SK_REPAIR 130|SK_SCIENCE 140@SK_REPAIR 130&SK_SCIENCE 140@PID_MOTIVATOR 1&PID_V15_COMPUTER_PART 1&PID_CRAFT_STEEL_PART 1&PID_STEEL 2&PID_CRAFT_POLYMER 8@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_LASER_PISTOL 1@exp 275 }
{207}{}{PID_MAGNETO_LASER_PISTOL@Низковольтный лазерный проектор этого пистолета оснащается магнитной системой калибровки. Она не дает энергии лазера рассеиваться, легко концентрируя ее на цели даже размером со спичечную головку.@SK_REPAIR 140|SK_SCIENCE 160@SK_REPAIR 140&SK_SCIENCE 160@PID_MOTIVATOR 2&PID_V15_COMPUTER_PART 2&PID_CRAFT_POLYMER 8@PID_CRAFT_AUTOFIX 1@PID_MAGNETO_LASER_PISTOL 1@exp 750 }
{208}{}{PID_223_PISTOL@Пистолет с самозарядным винтовочным затвором. Хитрая система заряжания занимает почти все пространство под рамой для экономии пространства. Оснащается дополнительным спусковым крючком, с помощью которого оружие стреляет в режиме вентилирования части пороховых газов, позволяющем погасить часть отдачи в ущерб силе выстрела.@SK_REPAIR 175|SK_SCIENCE 150@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_STEEL_PART 15&PID_STEEL 10&PID_CRAFT_POLYMER 2@PID_CRAFT_AUTOFIX 1@PID_223_PISTOL 1@exp 1500 }
{209}{}{PID_14MM_PISTOL@Центр тяжести этого крупнокалиберного самозарядного пистолета слегка смещается назад: пусть лучше отдача откидывает руку стрелка, чем травмирует ее. Возвратная пружина усиливается с целью полностью погасить энергию, получаемую затвором во время выстрела.@SK_REPAIR 175|SK_SCIENCE 175@SK_REPAIR 175&SK_SCIENCE 175@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 4&PID_STEEL 6&PID_CRAFT_POLYMER 2@PID_CRAFT_AUTOFIX 1@PID_14MM_PISTOL 1@exp 1500 }
{210}{}{PID_PLASMA_PISTOL@Спуск, плазменная камера и трансформатор у этого пистолета устанавливаются в ряд, отчего напоминают собой строение спусковой системы обычного пистолета. Из-за маленького объема камеры, она оснащается сразу двумя системами охлаждения по обе стороны ствола.@SK_REPAIR 150|SK_SCIENCE 175@SK_REPAIR 150&SK_SCIENCE 175@PID_CRAFT_CARBON 1&PID_PLASMA_TRANSFORMER 1&PID_V15_COMPUTER_PART 2&PID_CRAFT_POLYMER 1@PID_CRAFT_AUTOFIX 1@PID_PLASMA_PISTOL 1@exp 1500 }
{211}{}{PID_PLASMA_PISTOL_EXT_CART@Спуск, плазменная камера и трансформатор у этого пистолета устанавливаются в ряд, отчего напоминают собой строение спусковой системы обычного пистолета. Из-за маленького объема камеры, она оснащается сразу двумя системами охлаждения по обе стороны ствола. Сбоку устанавливается дополнительное гнездо для батарей.@SK_REPAIR 150&PE_PACK_RAT 1|SK_SCIENCE 175&PE_PACK_RAT 1@SK_REPAIR 150&SK_SCIENCE 175@PID_CRAFT_CARBON 1&PID_PLASMA_TRANSFORMER 1&PID_V15_COMPUTER_PART 2&PID_CRAFT_POLYMER 3@PID_CRAFT_AUTOFIX 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 1500 }
{300}{}{PID_SHOTGUN@Два гладких ствола, два спусковых крючка. Два курка и переломный затвор, взводящий их рычагом. Устройство этого дробовика ничем не отличается от устройства гладкоствольных охотничих ружей.@SK_REPAIR 125|SK_SCIENCE 75@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 10&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 2&PID_STEEL 2&PID_CRAFT_WOOD 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SHOTGUN 1@exp 250 }
{301}{}{PID_SAWED_OFF_SHOTGUN@Два гладких ствола, два спусковых крючка. Два курка и переломный затвор, взводящий их рычагом. Устройство этого дробовика ничем не отличается от устройства гладкоствольных охотничих ружей - кроме, разве что, укороченных донельзя стволов.@SK_REPAIR 125&PE_PACK_RAT 1|SK_SCIENCE 75&PE_PACK_RAT 1@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 8&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 2&PID_STEEL 2&PID_CRAFT_WOOD 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SAWED_OFF_SHOTGUN 1@exp 250 }
{302}{}{PID_REMMINGTON@Скользящее цевье этого дробовика двигает всю затворную группу механизмов, выбрасывая отстрелянную гильзу и заряжая новый патрон из подствольного трубчатого магазина. Стрелку при этом не нужно убирать руку с оружия до полной разрядки магазина.@SK_REPAIR 130|SK_SCIENCE 80@SK_REPAIR 130&SK_SCIENCE 80@PID_CRAFT_IRON_PART 8&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 3&PID_STEEL 3&PID_CRAFT_WOOD 3@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_REMMINGTON 1@exp 300 }
{303}{}{PID_TMS@Плазменная камера генерирует сгусток плазмы, который на спуске разбивается и рассеивается мощным импульсом по направлению выстрела. Камера при этом рассчитывается на повышенные, по сравнению с плазменным оружием, температуры. Корпус этого инструмента (или оружия, как угодно) изготавливается из металла для повышенной износостойкости.@SK_REPAIR 125|SK_SCIENCE 150@SK_REPAIR 125&SK_SCIENCE 150@PID_PLASMA_TRANSFORMER 1&PID_V15_COMPUTER_PART 2&PID_CRAFT_STEEL_PART 16&PID_STEEL 8&PID_CRAFT_POLYMER 2@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_TMS 1@exp 750 }
{304}{}{PID_TMDXL@Плазменная камера этого инструмента обязана выдерживать запредельные температуры, а раскаляемый ей плазмоид - плавить кусок горной породы в небольшую лужицу. На спуске сгусток плазмы распадается, мощным направленным импульсом поражая небольшую область по направлению выстрела.@SK_REPAIR 150|SK_SCIENCE 175@SK_REPAIR 150&SK_SCIENCE 175@PID_CRAFT_CARBON 1&PID_PLASMA_TRANSFORMER 1&PID_MOTIVATOR 1&PID_V15_COMPUTER_PART 1&PID_CRAFT_STEEL_PART 5&PID_STEEL 5@PID_CRAFT_AUTOFIX 1@PID_TMDXL 1@exp 1500 }
{305}{}{PID_COMBAT_SHOTGUN@Конструкция "буллпап" предполагает расположение магазина и автоматического спускового механизма за рукоятью со спусковым крючком. Стальная рама усиливает приклад и рукоять дробовика; цевье и гладкий ствол при этом изготавливаются из углепластика и облегченных полимеров.@SK_REPAIR 175|SK_SCIENCE 150@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 5&PID_STEEL 10&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_COMBAT_SHOTGUN 1@exp 1500 }
{306}{}{PID_PANCOR_JACKHAMMER@Автоматическое гладкоствольное ружье с самозарядным револьверным механизмом, конструкция "буллпап". Под давлением газов на надульник ствол сдвигается вперед, поворачивая штоком барабан и при возврате взводя курок. Собирается из композиции металла и углепластика в удобном полимерном корпусе.@SK_REPAIR 240&PE_SWIFT_LEARNER 1|SK_SCIENCE 220&PE_SWIFT_LEARNER 1@SK_REPAIR 240&SK_SCIENCE 220@PID_CRAFT_CARBON 3&PID_CRAFT_STEEL_PART 40&PID_STEEL 25&PID_CRAFT_POLYMER 45@PID_CRAFT_AUTOFIX 1@PID_PANCOR_JACKHAMMER 1@exp 4000 }
{400}{}{PID_10MM_SMG@Этот десятимиллиметровый пистолет-пулемет для быстрой перезарядки и ведения автоматического огня использует обратный ход отдачи ствола. Малогабаритность обеспечивается совмещением основного механизма и ствола - по сути, конструкция мало чем отличается от автоматического пистолета.@SK_REPAIR 125|SK_SCIENCE 75@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 10&PID_METAL_TRASH 2&PID_CRAFT_STEEL_PART 2&PID_STEEL 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_10MM_SMG 1@exp 250 }
{401}{}{PID_GREASE_GUN@Далеко не современная конструкция с автоматическим механизмом пистолетного калибра, размещаемого прямо за стволом, не особо способствует компактности оружия. Несмотря на это, сие и без того малогабаритное оружие было и остается очень дешевым и эффективным в производстве в силу простоты своего устройства.@SK_REPAIR 125|SK_SCIENCE 75@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 11&PID_METAL_TRASH 1&PID_CRAFT_STEEL_PART 3&PID_STEEL 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_GREASE_GUN 1@exp 300 }
{402}{}{PID_HK_P90C@Пистолет-пулемет в корпусе из прочной пластмассы, закрывающем металлическую раму, имеет конструкцию "буллпап". Магазин устанавливается поверх ствольной коробки, при этом патроны расположены горизонтально, перпендикулярно стволу и разворачиваются на 90 градусов перед подачей в патронник.@SK_REPAIR 175|SK_SCIENCE 150@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_STEEL_PART 16&PID_STEEL 24&PID_CRAFT_POLYMER 24@PID_CRAFT_AUTOFIX 1@PID_HK_P90C 1@exp 1500 }
{500}{}{PID_JAEGER@Однозарядная винтовка с клиновым затвором, обеспечивающим открывание и закрывание канала ствола путем поступательного движения затвора перпендикулярно оси ствола. Так как оружие сконструированно из металла, детали корпуса, рукоять и приклад изготавливаются полыми.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_IRON_PART 15&PID_METAL_TRASH 5&PID_CRAFT_STEEL_PART 5&PID_STEEL 5@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_JAEGER 1@exp 500 }
{501}{}{PID_SNIPER_RIFLE@Самозарядный затвор этой снайперской винтовки за счет газового поршня двигает всю затворную группу, отстреливая гильзу, заряжая новый патрон и взводя спусковой механизм для следующего выстрела. Длинный нарезной ствол усиливается специальной рамой в области цевья. Оружие оснащается оптическим снайперским прицелом.@SK_REPAIR 200|SK_SCIENCE 175@SK_REPAIR 200&SK_SCIENCE 150@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 15&PID_STEEL 15&PID_CRAFT_POLYMER 5&PID_CRAFT_WOOD 5@PID_CRAFT_AUTOFIX 1@PID_SNIPER_RIFLE 1@exp 2500 }
{502}{}{PID_LASER_SNIPER@Оснащенный системой цифровой калибровки лазерный проектор использует всю предоставляемую энергию заряда для создания максимально мощного луча. Такой тип лазера сохраняет часть энергии даже против дефлекторных поверхностей, пусть и не слишком эффективно с ними справляется, но при этом имеет усиленный поражающий фактор.@SK_REPAIR 175|SK_SCIENCE 200@SK_REPAIR 175&SK_SCIENCE 200@PID_CRAFT_CARBON 1&PID_MOTIVATOR 4&PID_V15_COMPUTER_PART 4&PID_CRAFT_STEEL_PART 10&PID_STEEL 1&PID_CRAFT_POLYMER 10@PID_CRAFT_AUTOFIX 1@PID_LASER_SNIPER 1@exp 2500 }
{600}{}{PID_HUNTING_RIFLE@Приклад и цевье винтовки изготавливаются из древесины; спусковой механизм, рама и ствол - металлические. Самозарядный механизм, взводящий затвор с каждым выстрелом, обеспечивает возможность стрелять непрерывно до разрядки магазина.@SK_REPAIR 125|SK_SCIENCE 100@SK_REPAIR 125&SK_SCIENCE 100@PID_CRAFT_IRON_PART 10&PID_METAL_TRASH 3&PID_CRAFT_STEEL_PART 2&PID_STEEL 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_HUNTING_RIFLE 1@exp 300 }
{601}{}{PID_SCOPED_HUNTING_RIFLE@Приклад и цевье винтовки изготавливаются из древесины; спусковой механизм, рама и ствол - металлические. Самозарядный механизм, взводящий затвор с каждым выстрелом, обеспечивает возможность стрелять непрерывно до разрядки магазина. Оснащается дополнительным комплектом оптического прицела для точной стрельбы на дистанции.@SK_REPAIR 125&PE_PACK_RAT 1|SK_SCIENCE 100&PE_PACK_RAT 1@SK_REPAIR 125&SK_SCIENCE 100@PID_CRAFT_IRON_PART 10&PID_METAL_TRASH 5&PID_CRAFT_STEEL_PART 2&PID_STEEL 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SCOPED_HUNTING_RIFLE 1@exp 300 }
{602}{}{PID_GECKO_SAR@Зарядный магазин оружия представлен двигающим затворную группу скользящим цевьем - так называемой помпой, движением руки стрелка подающей патрон из трубчатого подствольного механизма в затвор. Приклад изготавливается из дерева.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 32&PID_STEEL 18&PID_CRAFT_WOOD 5@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_GECKO_SAR 1@exp 750 }
{603}{}{PID_BPA@Огромная шайтан-труба со сквозным магазином. Сам магазин не подает боеприпасы в затвор, вместо этого затвор взводится сдвиганием магазина внутрь оружия до тех пор, пока следующий патрон не окажется заряженным. Опустевший магазин затем извлекается и заменяется.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 38&PID_STEEL 19@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_BPA 1@exp 750 }
{605}{}{PID_STRIKER@Самозарядное ружье с кассетной боеукладкой, корпусом и прикладом из облегченных полимеров и спусковым механизмом из высокопрочного карбона. Такой боезапас оружию явно не на один выстрел - так что его износостойкость должна соответствовать.@SK_REPAIR 200|SK_SCIENCE 150@SK_REPAIR 200&SK_SCIENCE 150@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 10&PID_STEEL 15&PID_CRAFT_POLYMER 30@PID_CRAFT_AUTOFIX 1@PID_STRIKER 1@exp 1500 }
{606}{}{PID_LASER_RIFLE_EXT_CAP@Мощный лазерный проектор, питаемый от сети атомной энергией микрореакторов, генерирует практически неотражаемый поток излучения, хорошо справляющийся даже с дефлекторными поверхностями. Вся электроника располагается в утяжеленной конструкции винтовки с фокусирующим стволом.@SK_REPAIR 150|SK_SCIENCE 200@SK_REPAIR 150&SK_SCIENCE 200@PID_CRAFT_CARBON 1&PID_MOTIVATOR 6&PID_V15_COMPUTER_PART 4&PID_CRAFT_STEEL_PART 10&PID_STEEL 5&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_LASER_RIFLE_EXT_CAP 1@exp 1500 }
{607}{}{PID_PID_LASER_RIFLE_UPGRADE@Мощный лазерный проектор, питаемый от сети атомной энергией микрореакторов, генерирует практически неотражаемый поток излучения, хорошо справляющийся даже с дефлекторными поверхностями. Вся электроника располагается в утяжеленной конструкции винтовки с фокусирующим стволом. Объем зарядника увеличивается с целью повышения емкости боезапаса.@SK_REPAIR 150&PE_PACK_RAT 1|SK_SCIENCE 200&PE_PACK_RAT 1@SK_REPAIR 150&SK_SCIENCE 200@PID_CRAFT_CARBON 1&PID_MOTIVATOR 6&PID_V15_COMPUTER_PART 4&PID_CRAFT_STEEL_PART 10&PID_STEEL 8&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_PID_LASER_RIFLE_UPGRADE 1@exp 1500 }
{608}{}{PID_PLASMA_RIFLE@Классическа плазменного вооружения, тяжелое плазменное ружье P94 подает сформированный в плазменной камере сгусток перегретой плазмы в спусковую систему, на высокой скорости выстреливающей плазмоидом по направлению фокусировщика. Тяжелое орудие, вся электроника которого располагается в бронированном износостойком композитном корпусе.@SK_REPAIR 160|SK_SCIENCE 210@SK_REPAIR 160&SK_SCIENCE 210@PID_CRAFT_CARBON 1&PID_PLASMA_TRANSFORMER 1&PID_MOTIVATOR 2&PID_V15_COMPUTER_PART 5&PID_CRAFT_STEEL_PART 20&PID_STEEL 5&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_PLASMA_RIFLE 1@exp 1750 }
{609}{}{PID_TURBO_PLASMA_RIFLE@Классическа плазменного вооружения, тяжелое турбоплазменное ружье P94 подает сформированный в плазменной камере сгусток перегретой плазмы в турбинную спусковую систему, разгоняющую плазмоид по направлению фокусировщика. Тяжелое орудие, вся электроника которого располагается в бронированном износостойком композитном корпусе.@SK_REPAIR 160&PE_PACK_RAT 1|SK_SCIENCE 210&PE_PACK_RAT 1@SK_REPAIR 160&SK_SCIENCE 210@PID_CRAFT_CARBON 1&PID_PLASMA_TRANSFORMER 1&PID_MOTIVATOR 2&PID_V15_COMPUTER_PART 5&PID_CRAFT_STEEL_PART 20&PID_STEEL 10&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_TURBO_PLASMA_RIFLE 1@exp 1750 }
{610}{}{PID_CLOCKWORK_RIFLE@Надежный составной револьверный мехонизм в конструкции этого оружия совмещается с рычагом, приводимым в действие замком на рукояти, который, в свою очередь, задействует группу зарядных механизмов для взведения курка. Все это совмещается с классической конструкцией боевой винтовки.@SK_REPAIR 210&PE_SWIFT_LEARNER 1|SK_SCIENCE 180&PE_SWIFT_LEARNER 1@SK_REPAIR 210&SK_SCIENCE 180@PID_CRAFT_CARBON 2&PID_CRAFT_STEEL_PART 15&PID_STEEL 15&PID_CRAFT_POLYMER 25@PID_CRAFT_AUTOFIX 1@PID_CLOCKWORK_RIFLE 1@exp 2500 }
{611}{}{PID_GALO@Основу металлического корпуса винтовки составляет каркасная рама из сверхпрочных сплавов. Сам механизм оружия представляет из себя тяжелый самозарядный спусковой механизм, заряжающий в затвор уложенные в барабан в вертикальном положении патроны.@SK_REPAIR 250&PE_SWIFT_LEARNER 1|SK_SCIENCE 225&PE_SWIFT_LEARNER 1@SK_REPAIR 250&SK_SCIENCE 225@PID_CRAFT_CARBON 3&PID_CRAFT_URANIUM_PLATE 1&PID_CRAFT_STEEL_PART 25&PID_STEEL 20&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_GALO 1@exp 4500 }
{700}{}{PID_TOMMY_GUN@Приклад и обе рукояти выполняются из дерева. Сам же автоматический затвор, по традиции располагающийся за стволом без экономии габаритов, под давлением остаточной энергии газа на спуске отстреливает гильзу, заряжая новый патрон из барабанного магазина.@SK_REPAIR 125|SK_SCIENCE 75@SK_REPAIR 125&SK_SCIENCE 75@PID_CRAFT_IRON_PART 12&PID_METAL_TRASH 3&PID_CRAFT_STEEL_PART 2&PID_STEEL 2&PID_CRAFT_WOOD 3@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_TOMMY_GUN 1@exp 300 }
{701}{}{PID_ASSAULT_RIFLE@Карабин непрерывного огня, собираемый по надежной и дешевой в производстве системе АК. Рукоять, приклад и цевье для удобства и экономии ресурсов изготавливаются из дерева.@SK_REPAIR 125|SK_SCIENCE 100@SK_REPAIR 125&SK_SCIENCE 100@PID_CRAFT_IRON_PART 10&PID_CRAFT_STEEL_PART 5&PID_STEEL 5&PID_CRAFT_WOOD 4@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_ASSAULT_RIFLE 1@exp 500 }
{702}{}{PID_ASSAULT_RIFLE_EXT_MAG@Карабин непрерывного огня, собираемый по надежной и дешевой в производстве системе АК. Рукоять, приклад и цевье для удобства и экономии ресурсов изготавливаются из дерева, повышается вместимость магазина с целью увеличения боезапаса.@SK_REPAIR 125&PE_PACK_RAT 1|SK_SCIENCE 100&PE_PACK_RAT 1@SK_REPAIR 125&SK_SCIENCE 100@PID_CRAFT_IRON_PART 10&PID_CRAFT_STEEL_PART 5&PID_STEEL 5&PID_CRAFT_WOOD 4@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 500 }
{703}{}{PID_LASER_RIFLE@Для лазерного проектора этого оружия изготавливается сеть электропитания, рассчитанная на очень быстрое потребление энергии батарей из магазина для ведения непрерывного огня. В остальном это обычная лазерная винтовка с фокусирующим стволом в корпусе старого образца.@SK_REPAIR 140|SK_SCIENCE 160@SK_REPAIR 140&SK_SCIENCE 160@PID_MOTIVATOR 2&PID_V15_COMPUTER_PART 2&PID_CRAFT_STEEL_PART 5&PID_STEEL 2&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_LASER_RIFLE 1@exp 750 }
{704}{}{PID_FN_FAL@Основа оружия - надежный композитный автоматический механизм с отводом пороховых газов, под патроны относительно крупного винтовочного калибра 7,62 миллиметра. Корпус и рама выполняются из облегченной стали; приклад, рукоять и цевье обиваются мягким пластиком для удобства.@SK_REPAIR 175|SK_SCIENCE 150@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 15&PID_STEEL 10&PID_CRAFT_POLYMER 5@PID_CRAFT_AUTOFIX 1@PID_FN_FAL 1@exp 1500 }
{705}{}{PID_FN_FAL_NIGHT_SCOPE@Основа оружия - надежный композитный автоматический механизм с отводом пороховых газов, под патроны относительно крупного винтовочного калибра 7,62 миллиметра. Корпус и рама выполняются из облегченной стали; приклад, рукоять и цевье обиваются мягким пластиком для удобства. Дополнительно устанавливается лазерный целеуказатель, повышающий точность стрельбы.@SK_REPAIR 175&PE_PACK_RAT 1|SK_SCIENCE 150&PE_PACK_RAT 1@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_CARBON 1&PID_V15_COMPUTER_PART 1&PID_CRAFT_STEEL_PART 15&PID_STEEL 10&PID_CRAFT_POLYMER 6@PID_CRAFT_AUTOFIX 1@PID_FN_FAL_NIGHT_SCOPE 1@exp 1500 }
{706}{}{PID_BROWNING@Автоматическая винтовка с расположенной в направляющей трубке возвратной пружиной, рычажным запиранием затвора и отводом пороховых газов через подствольный газоотводный узел. Такая относительно незамысловатая и надежная конструкция, будучи выполненной из заводских композитов последнего поколения, ничем не уступает по боевым показателям современным аналогам, сохраняя износостойкость и простоту оригинала.@SK_REPAIR 240&PE_SWIFT_LEARNER 1|SK_SCIENCE 220&PE_SWIFT_LEARNER 1@SK_REPAIR 240&SK_SCIENCE 220@PID_CRAFT_CARBON 2&PID_CRAFT_STEEL_PART 75&PID_STEEL 50&PID_CRAFT_POLYMER 10&PID_CRAFT_WOOD 10@PID_CRAFT_AUTOFIX 1@PID_BROWNING 1@exp 4250 }
{707}{}{PID_INDEPENDENT@Крайне малогабаритный спусковой и заряжающий механизм конструкции "буллпап" под малокалиберные пятимиллиметровые патроны помещается в легко разбираемый корпус из прочных полимеров, крепящихся к облегченной металлической раме. В отличии от оригиналов образца, это оружие, впрочем, когда-нибудь да сломается.@SK_REPAIR 250&PE_SWIFT_LEARNER 1|SK_SCIENCE 225&PE_SWIFT_LEARNER 1@SK_REPAIR 250&SK_SCIENCE 225@PID_CRAFT_CARBON 4&PID_CRAFT_STEEL_PART 5&PID_STEEL 10&PID_CRAFT_POLYMER 20@PID_CRAFT_AUTOFIX 1@PID_INDEPENDENT 1@exp 4250 }
{708}{}{PID_HEAVY_LASER_ASSAULT@Мощный лазерный проектор, питаемый от сети атомной энергией микрореакторов, генерирует практически неотражаемые потоки излучения с огромной скоростью. Высококачественная оружейная сеть, рассчитанная на огромные перегрузки, очень быстро потребляет и трансформирует энергию микрореакторов, позволяя подключенному к фокусирующему стволу лазерному проектору не прекращать огонь ни на секунду.@SK_REPAIR 225&PE_SWIFT_LEARNER 1|SK_SCIENCE 250&PE_SWIFT_LEARNER 1@SK_REPAIR 225&SK_SCIENCE 250@PID_CRAFT_CARBON 3&PID_MOTIVATOR 5&PID_V15_COMPUTER_PART 10&PID_CRAFT_STEEL_PART 15&PID_STEEL 5&PID_CRAFT_POLYMER 30@PID_CRAFT_AUTOFIX 1@PID_HEAVY_LASER_ASSAULT 1@exp 4500 }
{800}{}{PID_LIGHT_SUPPORT_WEAPON@Классический механизм непрерывного огня с отводом пороховых газов через поршень устанавливается в конструкции "буллпап" с зарядным механизмом на уровне приклада. Приклад и цевье в целях удешевления производства выполняются из дерева.@SK_REPAIR 150|SK_SCIENCE 100@SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 30&PID_STEEL 15&PID_CRAFT_POLYMER 2&PID_CRAFT_WOOD 5@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 750 }
{801}{}{PID_M60@Пулемет с автоматической системой перезаряжания лентопротяжного механизма при помощи газового двигателя, с воздушным охлаждением и удобным деревянным цевьем и прикладом. Оснащается кассетой под ленту патронов триста восьмого калибра и сошками для ведения стрельбы из положения лежа.@SK_REPAIR 200|SK_SCIENCE 150@SK_REPAIR 200&SK_SCIENCE 150@PID_CRAFT_CARBON 1&PID_CRAFT_STEEL_PART 10&PID_STEEL 10&PID_CRAFT_WOOD 10@PID_CRAFT_AUTOFIX 1@PID_M60 1@exp 2500 }
{802}{}{PID_BOZAR@Сверхточное автоматическое оружие, использующее для стрельбы патроны 223 калибра. Корпус тяжелой пулеметной винтовки скрывает в себе скорострельный спусковой механизм с нарезным стволом для стрельбы на большие дистанции с меткостью орудующего скальпелем хирурга.@SK_REPAIR 250&PE_SWIFT_LEARNER 1|SK_SCIENCE 225&PE_SWIFT_LEARNER 1@SK_REPAIR 250&SK_SCIENCE 225@PID_CRAFT_CARBON 4&PID_CRAFT_STEEL_PART 10&PID_STEEL 10&PID_CRAFT_POLYMER 10@PID_CRAFT_AUTOFIX 1@PID_BOZAR 1@exp 4500 }
{900}{}{PID_COCKLISHER@Несложный механизм с переломным затвором, через который заряжается боеприпас, и который взводит курок для выстрела по нажатию спускового крючка. Как простое гладкоствольное ружье, только гранатометного калибра.@SK_REPAIR 125|SK_SCIENCE 100@SK_REPAIR 125&SK_SCIENCE 100@PID_CRAFT_STEEL_PART 10&PID_STEEL 10&PID_CRAFT_IRON_PART 20&PID_METAL_TRASH 10&PID_CRAFT_POLYMER 5@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_COCKLISHER 1@exp 1000 }
{901}{}{PID_MGL@Многозарядный ручной гранатомет по сути состоит из трех частей: рукояти со взводным и спусковым механизмом, барабана с механизмом вращения, и ствола с дополнительной рукоятью.@SK_REPAIR 175|SK_SCIENCE 150@SK_REPAIR 175&SK_SCIENCE 150@PID_CRAFT_CARBON 2&PID_CRAFT_STEEL_PART 10&PID_STEEL 15&PID_CRAFT_POLYMER 15@PID_CRAFT_AUTOFIX 1@PID_MGL 1@exp 3000 }
{902}{}{PID_ROCKET_LAUNCHER@Сам гранатометный механизм представляет из себя ствол с фиксатором для реактивной гранаты, раструб для полного отвода реактивного выхлопа и рукояти со спусковым крючком, соединенным с ударным спусковым механизмом. Дополнительно оружие оснащается цифровой аппаратурой для наводки и прицеливания.@SK_REPAIR 250&PE_SWIFT_LEARNER 1|SK_SCIENCE 225&PE_SWIFT_LEARNER 1@SK_REPAIR 250&SK_SCIENCE 225@PID_CRAFT_CARBON 4&PID_MOTIVATOR 1&PID_V15_COMPUTER_PART 2&PID_CRAFT_STEEL_PART 10&PID_STEEL 15&PID_CRAFT_POLYMER 25@PID_CRAFT_AUTOFIX 1@PID_ROCKET_LAUNCHER 1@exp 6000 }
{1000}{}{PID_FLAMER@Для тех, кто не в курсе, боевая конструкция огнемета состоит из баллона для топлива, компрессора, давлением придающего ускорение горючему при выстреле, и запальника на распылителе. Прочный корпус из термостойкой стали позволяет свести вероятность поломки при ошибке оператора к минимуму.@SK_REPAIR 150|SK_SCIENCE 125@SK_REPAIR 150&SK_SCIENCE 125@PID_CRAFT_STEEL_PART 35&PID_STEEL 15&PID_CRAFT_POLYMER 5@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_FLAMER 1@exp 1250 }
{1001}{}{PID_IMPROVED_FLAMETHROWER@Усовершенствованная конструкция огнемета, подающая топливо за счет находящейся перед выстрелом под давлением компрессорной камеры и воспламеняющая его еще до распыления установленным в конструкцию запальником. Ввиду подобных особенностей, в констуркции применяются высококачественные термостойкие композиционные материалы.@SK_REPAIR 200|SK_SCIENCE 150@SK_REPAIR 200&SK_SCIENCE 150@PID_CRAFT_CARBON 2&PID_CRAFT_STEEL_PART 30&PID_STEEL 20&PID_CRAFT_POLYMER 10@PID_CRAFT_AUTOFIX 1@PID_IMPROVED_FLAMETHROWER 1@exp 3500 }
{2000}{}{PID_SANDROBE@Обыкновенная однослойная роба - такую работу будет легко выполнить даже начинающему портному. Выполняется либо в виде рубашки с длинным подолом и капюшоном, либо, для ленивых, в виде целого полотна с пришитыми рукавами и зауженными воротником и талией.@SK_OUTDOORSMAN 50@SK_OUTDOORSMAN 50@PID_RAGS 20&PID_POCKET_LINT 10@PID_SHIV 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_SANDROBE 1@exp 150 }
{2010}{}{PID_LEATHER_JACKET@Комплект одежды из прочной кожи с прошитыми крепкой нитью внутренними швами. Дополнительно подбивается прокладкой из мягкой ткани для удобства ношения.@SK_OUTDOORSMAN 75@SK_OUTDOORSMAN 75@PID_CRAFT_LEATHER 12&PID_RAGS 10&PID_POCKET_LINT 15@PID_SHIV 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_LEATHER_JACKET 1@exp 250 }
{2011}{}{PID_CURED_LEATHER_ARMOR@Комплект крепкой одежды из прочной кожи с прошитыми крепкой нитью внутренними швами и дополнительными металлическми деталями, вроде заклепок и шипов, которые не только придают ей прочности, но и внушительно смотрятся.@SK_OUTDOORSMAN 150@SK_OUTDOORSMAN 150@PID_CRAFT_LEATHER 20&PID_RAGS 10&PID_POCKET_LINT 15&PID_CRAFT_IRON_PART 2@PID_SHIV 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_CURED_LEATHER_ARMOR 1@exp 500 }
{2012}{}{PID_KEVLAR_JACKET@Основа одежды из плотных кожаных фрагментов, оснащенных карбонопластиковыми креплениями для повышенной прочности, обивается полиамидной тканью для защиты от механических повреждений. Все это затем с наружней части обшивается тонкой дубленой кожей для износостойкости и удешевления косметического ремонта. Внутрь одежде для удобства ношения вшивается мягкая льняная подкладка.@SK_OUTDOORSMAN 200&PE_SWIFT_LEARNER 1|SK_SCIENCE 200&PE_SWIFT_LEARNER 1@SK_OUTDOORSMAN 200&SK_SCIENCE 200@PID_CRAFT_CARBON 1&PID_CRAFT_POLYMER 20&PID_CRAFT_LEATHER 20&PID_RAGS 10&PID_POCKET_LINT 20@PID_CRAFT_AUTOFIX 1@PID_KEVLAR_JACKET 1@exp 2500 }
{2020}{}{PID_LEATHER_ARMOR@Броня представляет из себя комплект одежды, усиленный многослоыными твердыми кожаными пластинами в местах вероятных попаданий. Все защитные элементы соединяются между собой стяжками и креплениями, образуя подобие вшитого в одежду жилета.@SK_OUTDOORSMAN 125|SK_SCIENCE 50@SK_OUTDOORSMAN 125&SK_SCIENCE 50@PID_CRAFT_LEATHER 30&PID_RAGS 5&PID_POCKET_LINT 20@PID_SHIV 1|PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_LEATHER_ARMOR 1@exp 500 }
{2021}{}{PID_LEATHER_ARMOR_MK_II@Комплект многослойной одежды из твердой дубленой кожи с прочной каркасной прослойкой, к которой намертво прибиты металлическими заклепками прочные кожаные пластины.@SK_OUTDOORSMAN 150|SK_SCIENCE 75@SK_OUTDOORSMAN 150&SK_SCIENCE 75@PID_CRAFT_LEATHER 35&PID_CRAFT_IRON_PART 4&PID_RAGS 5&PID_POCKET_LINT 25@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_LEATHER_ARMOR_MK_II 1@exp 1000 }
{2022}{}{PID_CHITIN_VEST@Кожаный жилет обшивается хитиновыми фрагментами, словно пластичнатый доспех. Укладка пластин нагрудника при этом может повторять мышцы человеческого тела для повышенной брутальности.@SK_OUTDOORSMAN 150|SK_SCIENCE 100@SK_OUTDOORSMAN 150&SK_SCIENCE 100@PID_CRAFT_LEATHER 15&PID_VACCINE 20&PID_POCKET_LINT 20@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_CHITIN_VEST 1@exp 1500 }
{2023}{}{PID_CHITIN_ARMOR@На комплект кожаной одежды нашиваются заранее сформированные из хитиновых фрагментов защитные пластины по форме классической американской пехотной брони. Для повышения надежности, пластины скрепляются между собой стяжками.@SK_OUTDOORSMAN 175|SK_SCIENCE 125@SK_OUTDOORSMAN 175&SK_SCIENCE 125&SK_REPAIR 75@PID_CRAFT_LEATHER 20&PID_VACCINE 60&PID_POCKET_LINT 30&PID_CRAFT_STEEL_PART 5@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_CHITIN_ARMOR 1@exp 2000 }
{2024}{}{PID_CHITIN_ARMOR_MK_II@На комплект кожаной одежды нашиваются заранее сформированнй из хитиновых фрагментов защитный панцирь, подобный тем, что используются в тяжелых образцах боевой пехотной брони. Бронирование рук и ног представлено нашитыми на кожаный каркас защитными хитиновыми пластинками.@SK_OUTDOORSMAN 200|SK_SCIENCE 150@SK_OUTDOORSMAN 200&SK_SCIENCE 150&SK_REPAIR 75@PID_CRAFT_LEATHER 25&PID_VACCINE 90&PID_POCKET_LINT 40&PID_CRAFT_STEEL_PART 8@PID_SUPER_TOOL_KIT 1|PID_CRAFT_AUTOFIX 1@PID_CHITIN_ARMOR_MK_II 1@exp 2250 }
{2030}{}{PID_COMBAT_ARMOR@Легкая пехотная боевая броня представляет собой набор из нагрудника, шлема и нескольких защитных пластин для разных частей тел, выполненных из композиции металла и прочных полимерных соединений. Производится в комплекте с униформой и дополнительной защитной экипировкой из более легких материалов, вроде кевлара и кожи.@SK_OUTDOORSMAN 200|SK_SCIENCE 175@SK_OUTDOORSMAN 200&SK_SCIENCE 175&SK_REPAIR 100@PID_CRAFT_STEEL_PART 10&PID_CRAFT_POLYMER 40&PID_CRAFT_LEATHER 10&PID_RAGS 30&PID_POCKET_LINT 30@PID_CRAFT_AUTOFIX 1@PID_COMBAT_ARMOR 1@exp 2500 }
{2031}{}{PID_COMBAT_ARMOR_MK_II@Тяжелая пехотная боевая броня представляет собой набор из униформы, закрывающего корпус стрелка панциря и экипировки для защиты конечностей из композиции металла и прочных полимерных соединений. Дополняется все это шлемом со стеклянным визором и аксессуарами из кожи и кевлара.@SK_OUTDOORSMAN 210|SK_SCIENCE 180@SK_OUTDOORSMAN 210&SK_SCIENCE 180&SK_REPAIR 100@PID_CRAFT_STEEL_PART 20&PID_CRAFT_POLYMER 50&PID_CRAFT_LEATHER 5&PID_RAGS 25&PID_POCKET_LINT 30@PID_CRAFT_AUTOFIX 1@PID_COMBAT_ARMOR_MK_II 1@exp 3000 }
{3000}{}{PID_HEALING_POWDER@Если правильно растолочь в равном количестве соцветия брока и корни зандер до состояния пудры и смешать, можно впоследствии использовать получившуюся субстанцию для внутреннего и местного применения при легких ранениях.@SK_OUTDOORSMAN 100@SK_OUTDOORSMAN 100@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1@@PID_HEALING_POWDER 1@exp 50 }
{3001}{}{PID_STIMPAK@Коктейль из протеина, формирующего новые клетки, цинка, витаминов A, C, E, и гормонов, запускающих биологические процессы организма, смешивается по довоенной медицинской формуле в комбинаторе вашего фабрикатора и затем закачивается по давлением в одноразовые шприцы.@SK_DOCTOR 125|SK_SCIENCE 125@SK_DOCTOR 125&SK_SCIENCE 125@PID_MEDICAL_SUPPLIES 3&PID_HYPODERMIC_NEEDLE 5@PID_CRAFT_AUTOFIX 1@PID_STIMPAK 5@exp 500 }
{3002}{}{PID_SUPER_STIMPAK@Стимпак, адреналин, морфин, анестетики и прочие препараты распределяются по ампулам капельницы для постепенного поступления в организм пострадавшего.@SK_DOCTOR 125&PE_SWIFT_LEARNER 1|SK_SCIENCE 125&PE_SWIFT_LEARNER 1@SK_DOCTOR 125&SK_SCIENCE 125&SK_REPAIR 50&SK_OUTDOORSMAN 75@PID_STIMPAK 1&PID_MEDICAL_SUPPLIES 2&PID_CRAFT_POLYMER 2@PID_CRAFT_AUTOFIX 1@PID_SUPER_STIMPAK 1@exp 500 }
{3003}{}{PID_MENTATS@Добытый из яда грибов стимулянт-галлюциноген смешивается с легкими нейротропами для получения действующего вещества, схожего по принципу влияния на ЦНС с оригинальными ментатами. Все это готовится в сиропе из нюка-колы и мутафруктов для получения сахарных леденцов - таблеток в их готовом виде.@SK_DOCTOR 150|SK_SCIENCE 125@SK_DOCTOR 150&SK_SCIENCE 125&SK_OUTDOORSMAN 100@PID_MOUSE_SKIN 15&PID_MEDICAL_SUPPLIES 1&PID_NUKA_COLA 1&PID_MUTATED_FRUIT 2@PID_CRAFT_AUTOFIX 1@PID_MENTATS 1@exp 500 }
{3004}{}{PID_BUFFOUT@Анаболики и стимулирующие выделение энергии гормоны в таблетках из мела и растительной клетчатки для ускоренного усвоения.@SK_DOCTOR 150|SK_SCIENCE 125@SK_DOCTOR 150&SK_SCIENCE 125&SK_OUTDOORSMAN 100@PID_MEDICAL_SUPPLIES 2&PID_MINERAL 1&PID_XANDER_ROOT 5@PID_CRAFT_AUTOFIX 1@PID_BUFFOUT 1@exp 500 }
{3005}{}{PID_JET@Заветный протеиновый экстракт нежелающий разгребать кучи браминьего дерьма может получить из мяса не первой свежести путем фильтрации через воду, при этом ряд компонентов заменяется на искусственные. Спирт используется в качестве катализатора на последних стадиях приготовления.@SK_DOCTOR 100|SK_SCIENCE 180@SK_DOCTOR 100&SK_SCIENCE 180&SK_OUTDOORSMAN 100@PID_MEAT 20&PID_MEDICAL_SUPPLIES 1&PID_BOTTLE_FULL 2&PID_BOOZE 1@PID_CRAFT_AUTOFIX 1@PID_JET 1@exp 750 }
{3006}{}{PID_PSYCHO@Смесь из созданных в лабораторных условиях химических компонентов, содержащая в себе гормоны и мощные нейростимуляторы, а также ресурсы обмена веществ в виде протеина, цинка, витаминов и минералов.@SK_SCIENCE 200|SK_DOCTOR 200@SK_SCIENCE 250&SK_DOCTOR 200@PID_MEDICAL_SUPPLIES 10@PID_CRAFT_AUTOFIX 1@PID_PSYCHO 1@exp 1000 }
{3007}{}{PID_DETOXIN@Неважно, какое действующее вещество вы выберете: если его требуется принимать внутрь, самый лучший способ доставить его в организм - это смешать со смесью гидрокарбоната натрия и крахмала, спрессовав в небольшие таблетки для глотания. Сервировать со стаканом воды.@SK_DOCTOR 175|SK_SCIENCE 125@SK_DOCTOR 175&SK_SCIENCE 125@PID_RAGS 3&PID_BOOZE 1&PID_METAL_TRASH 1&PID_POCKET_LINT 1&PID_DETOXIN 1@@PID_FIRST_AID_KIT 1@exp 200 }
{3010}{}{PID_FIRST_AID_KIT@Время поиграть в больничку: собираем в один комплект перевязочный материал, спирт для обеззараживания, одноразовый зажим, одноразовую иглу, крепкую нить для наложения швов и пару таблеток болеутоляющего. Комплект кладем в аптечку, которую затем возим с собой в машине и никогда не используем.@SK_DOCTOR 150|SK_OUTDOORSMAN 100@SK_DOCTOR 150&SK_OUTDOORSMAN 100@PID_RAGS 3&PID_BOOZE 1&PID_METAL_TRASH 1&PID_POCKET_LINT 1&PID_DETOXIN 1@@PID_FIRST_AID_KIT 1@exp 200 }
{3011}{}{PID_DOCTORS_BAG@Что включают в себя расходники для серьезных операций? Правильно, еще больше перевязочного материала, нитей для швов, спирта для обеззараживания и мощный анестетик, чем в обычной аптечке. Ну и, конечно же, набор хирургических инструментов из качественной стали.@SK_DOCTOR 150|SK_OUTDOORSMAN 100@SK_DOCTOR 150&SK_OUTDOORSMAN 100@PID_RAGS 5&PID_BOOZE 2&PID_STEEL 2&PID_POCKET_LINT 2&PID_DETOXIN 1@@PID_DOCTORS_BAG 1@exp 250 }